<?php

require_once ("templates/header.phtml");

?>

<div class="column box is-narrow m-3 table-container">
    <div class="title has-text-centered">My Friends</div>
    <div class="tabs is-centered is-toggle">
        <ul>
            <li class="is-active"><a>Current Friends</a></li>
            <li><a href="friendRequests.php">Friend Requests</a></li>
        </ul>
    </div>

    <?php require_once("Views/templates/tables/table.phtml"); ?>

</div>

<?php

require_once ("templates/footer.phtml");

?>
