            </div>
            <footer class="footer column is-narrow">
                <div class="content has-text-centered">
                    <p>
                        Made by <strong>Shimon Travers</strong>.
                    </p>
                    <p>
                        Last updated on <strong><em>Wednesday 17<sup>th</sup> November 2021</em></strong>
                    </p>
                </div>
            </footer>
        </div>
    </body>
</html>