<!DOCTYPE html>
<html lang="en" class="has-navbar-fixed-top">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta charset="UTF-8">
        <title>Home</title>
        <link rel="stylesheet" href="css/bulma.min.css">
        <link rel="stylesheet" href="css/custom.css">
    </head>
    <body>
        <div class="columns is-flex-direction-column">
            <header class="column is-narrow">
                <nav class="navbar is-info is-fixed-top" role="navigation" aria-label="main navigation">
                    <div class="navbar-brand">
                        <a class="navbar-item" href="index.php">
                            <img src="images/logo.png" height="100px">
                        </a>

                        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasic">
                            <span aria-hidden="true"></span>
                            <span aria-hidden="true"></span>
                            <span aria-hidden="true"></span>
                        </a>
                    </div>

                    <div id="navbarBasic" class="navbar-menu">
                        <div class="navbar-start">
                            <a class="navbar-item" href="/">
                                Home
                            </a>

                            <a class="navbar-item" href="friends.php">
                                Friends
                            </a>
                        </div>

                        <div class="navbar-end">
                            <div class="navbar-item dropdown is-right is-hoverable">
                                <div class="dropdown-trigger">
                                    <a class="navbar-link" aria-haspopup="true" aria-controls="dropdown-menu">
                                        <?php
                                            if (isset($_SESSION["id"])) {
                                                echo 'Hello '.$_SESSION["username"];
                                            } else {
                                                echo 'Login / Sign up';
                                            }
                                        ?>
                                    </a>
                                </div>

                                <div class="dropdown-menu" id="dropdown-menu" role="menu">
                                    <div class="dropdown-content">
                                        <div class="dropdown-item">
                                            <?php
                                                if (isset($_SESSION["id"])) {
                                                    require_once ("Views/templates/userProfile.phtml");
                                                } else {
                                                    require_once("Views/templates/headerLogin.phtml");
                                                }
                                            ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </nav>
            </header>
            <div class="columns is-centered">
