<div class="modal is-active">
    <div class="modal-background"></div>
    <div class="modal-card">
        <header class="modal-card-head">
            <p class="modal-card-title">Edit Details</p>
            <a href="profile.php" class="delete" aria-label="close"></a>
        </header>
        <form method="POST" action="profile.php">
            <section class="modal-card-body">
                <?php
                if (isset($error->errorMessage)) {
                    echo '<div class="columns is-centered"><div class="column is-narrow">';
                    echo '<div class="notification is-danger">'.$error->errorMessage.'</div>';
                    echo '</div></div>';
                }
                ?>
                <div class="field">
                    <label class="label">Enter you current password</label>
                    <div class="control">
                        <input name="oldPassword" class="input" type="password" placeholder="Old Password" required>
                    </div>
                </div>
                <div class="field">
                    <label class="label">Choose a new password</label>
                    <div class="control">
                        <input name="password1" class="input" type="password" placeholder="New Password" required>
                    </div>
                </div>
                <div class="field">
                    <label class="label">Repeat your new password</label>
                    <div class="control">
                        <input name="password2" class="input" type="password" placeholder="Repeat New Password" required>
                    </div>
                </div>
            </section>
            <footer class="modal-card-foot">
                <button name="password" class="button is-success">Save changes</button>
                <a href="profile.php" class="button">Cancel</a>
            </footer>
        </form>
    </div>
</div>